const Booking = require('../models/Booking');
const Order = require('../models/Order');
const User = require('../models/User');
const PartnerNotification = require('../models/PartnerNotification');
const { sendEmail } = require('./email');
const { buildPdf } = require('./invoicePdf');
const { enqueueJob } = require('./jobQueue');

const clean = (value) => String(value || '').trim();
const money = (value) => `INR ${Number(value || 0).toLocaleString('en-IN')}`;
const dateText = (value) => (value ? new Date(value).toLocaleDateString('en-IN') : '');

const escapeHtml = (value) =>
  clean(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const tableHtml = (rows) => `
  <table cellpadding="0" cellspacing="0" role="presentation" style="width:100%;border-collapse:collapse;margin-top:14px">
    ${rows
      .filter(([, value]) => value !== undefined && value !== null && clean(value) !== '')
      .map(([label, value]) => `
        <tr>
          <td style="padding:10px 12px;border:1px solid #eadfc7;background:#fff8ea;color:#6f4b12;font:600 13px Arial,sans-serif;width:38%">${escapeHtml(label)}</td>
          <td style="padding:10px 12px;border:1px solid #eadfc7;color:#2b2018;font:13px Arial,sans-serif">${escapeHtml(value)}</td>
        </tr>
      `)
      .join('')}
  </table>
`;

const logoUrl = () => {
  const base = clean(process.env.FRONTEND_BASE_URL || process.env.PUBLIC_SITE_URL);
  if (!base) return '';
  try {
    return new URL('/vrindasarthi%20logo.jpeg', base).toString();
  } catch {
    return '';
  }
};

const emailShell = ({ title, intro, rows, totalLabel = 'Total', totalAmount = 0, reason = '' }) => `
  <div style="margin:0;padding:0;background:#f7f3ec">
    <div style="max-width:680px;margin:0 auto;padding:24px 12px">
      <div style="background:#2b120d;color:#f7c948;padding:16px 22px;border-radius:12px 12px 0 0;font:700 22px Georgia,serif;display:flex;align-items:center;gap:12px">
        ${logoUrl() ? `<img src="${logoUrl()}" alt="Vrindavan Sarthi" width="44" height="44" style="width:44px;height:44px;border-radius:50%;object-fit:cover;border:1px solid #f7c948" />` : ''}
        <span>Vrindavan Sarthi</span>
      </div>
      <div style="background:#fff;border:1px solid #eadfc7;border-top:0;border-radius:0 0 12px 12px;padding:22px">
        <h1 style="margin:0 0 8px;color:#2b2018;font:700 22px Arial,sans-serif">${escapeHtml(title)}</h1>
        <p style="margin:0;color:#6b6259;font:14px/1.6 Arial,sans-serif">${escapeHtml(intro)}</p>
        ${reason ? `<div style="margin-top:16px;padding:12px 14px;border-radius:8px;background:#fff3f0;border:1px solid #ffc7bd;color:#8a2416;font:14px Arial,sans-serif"><b>Reason:</b> ${escapeHtml(reason)}</div>` : ''}
        ${tableHtml(rows)}
        <div style="margin-top:18px;padding:14px 16px;border-radius:10px;background:#f7c948;color:#2b120d;font:700 18px Arial,sans-serif;display:flex;justify-content:space-between">
          <span>${escapeHtml(totalLabel)}</span><span>${escapeHtml(money(totalAmount))}</span>
        </div>
        <p style="margin:18px 0 0;color:#8a8178;font:12px/1.5 Arial,sans-serif">This email was generated by Vrindavan Sarthi. Please keep it for your records.</p>
      </div>
    </div>
  </div>
`;

const bookingRows = (booking) => [
  ['Booking ID', booking.bookingId],
  ['Service Type', booking.bookingType],
  ['Service Name', booking.itemName],
  ['Customer', booking.customerFullName || booking.userName],
  ['Mobile', booking.customerMobile || booking.userPhone],
  ['Email', booking.customerEmail || booking.userEmail],
  ['Partner', booking.partnerName],
  ['Check-in / Travel Date', booking.pickupDate || dateText(booking.checkIn)],
  ['Check-out', dateText(booking.checkOut)],
  ['Route', booking.bookingType === 'cab' ? `${booking.pickupLocation} to ${booking.dropLocation}` : ''],
  ['Pickup Time', booking.pickupTime],
  ['Cab Type', booking.cabType || booking.assignedVehicleType],
  ['Guests / Passengers', booking.guests],
  ['Room Number', booking.roomNumber],
  ['Base Amount', money(booking.baseAmount || booking.checkoutSubtotal)],
  ['GST', Number(booking.taxAmount || 0) ? `${money(booking.taxAmount)} (${Number(booking.taxPercent || 0)}%)` : ''],
  ['Convenience Fee', money(booking.convenienceFeeAmount)],
  ['Advance Paid', money(booking.advanceAmount)],
  ['Balance Payable', money(booking.balanceAmount)],
  ['Payment Option', booking.paymentOption === 'advance_30' ? '30% advance' : 'Full payment'],
  ['Payment Status', booking.paymentStatus],
  ['UPI Transaction ID', booking.upiTransactionId],
];

const orderRows = (order) => [
  ['Order ID', order.orderId],
  ['Tracking ID', order.trackingId],
  ['Product', order.productName],
  ['Quantity', order.quantity],
  ['Unit Price', money(order.productPrice)],
  ['Customer', order.userName],
  ['Mobile', order.userPhone],
  ['Email', order.userEmail],
  ['Shipping Address', order.shippingAddress],
  ['Payment Status', order.paymentStatus],
  ['Order Status', order.orderStatus],
  ['UPI Transaction ID', order.upiTransactionId],
  ['Courier', order.courierName],
  ['AWB Number', order.awbNumber],
];

const sendBookingInvoice = async (booking) => {
  const to = clean(booking.customerEmail || booking.userEmail);
  if (!to || booking.invoiceSentAt) return;
  const rows = bookingRows(booking);
  await sendEmail({
    to,
    subject: `Vrindavan Sarthi booking invoice ${booking.bookingId}`,
    text: ['Vrindavan Sarthi booking invoice', ...rows.map(([k, v]) => `${k}: ${v}`)].join('\n'),
    html: emailShell({
      title: 'Booking invoice',
      intro: 'Your payment has been verified. Here are the complete booking and payment details.',
      rows,
      totalAmount: booking.totalAmount,
    }),
    attachments: [{ filename: `invoice-${booking.bookingId}.pdf`, content: buildPdf({ title: `Invoice ${booking.bookingId}`, sections: [{ title: 'Booking Details', rows }] }), contentType: 'application/pdf' }],
  });
};

const sendOrderInvoice = async (order) => {
  const to = clean(order.userEmail);
  if (!to || order.invoiceSentAt) return;
  const rows = orderRows(order);
  await sendEmail({
    to,
    subject: `Vrindavan Sarthi order invoice ${order.orderId}`,
    text: ['Vrindavan Sarthi order invoice', ...rows.map(([k, v]) => `${k}: ${v}`)].join('\n'),
    html: emailShell({
      title: 'Order invoice',
      intro: 'Your order payment has been verified. Here are the product, delivery, and payment details.',
      rows,
      totalAmount: order.totalAmount,
    }),
    attachments: [{ filename: `invoice-${order.orderId}.pdf`, content: buildPdf({ title: `Invoice ${order.orderId}`, sections: [{ title: 'Order Details', rows }] }), contentType: 'application/pdf' }],
  });
};

const sendBookingCancellationEmail = async (booking, reason) => {
  const to = clean(booking.customerEmail || booking.userEmail);
  if (!to) return;
  await sendEmail({
    to,
    subject: `Booking cancelled ${booking.bookingId}`,
    text: `Your Vrindavan Sarthi booking ${booking.bookingId} has been cancelled.\nReason: ${reason}`,
    html: emailShell({
      title: 'Booking cancelled',
      intro: 'Your booking has been cancelled. The reason is shown below with your booking details.',
      rows: bookingRows(booking),
      totalLabel: 'Booking Value',
      totalAmount: booking.totalAmount,
      reason,
    }),
  });
};

const sendOrderCancellationEmail = async (order, reason) => {
  const to = clean(order.userEmail);
  if (!to) return;
  await sendEmail({
    to,
    subject: `Order cancelled ${order.orderId}`,
    text: `Your Vrindavan Sarthi order ${order.orderId} has been cancelled.\nReason: ${reason}`,
    html: emailShell({
      title: 'Order cancelled',
      intro: 'Your order has been cancelled. The reason is shown below with your order details.',
      rows: orderRows(order),
      totalLabel: 'Order Value',
      totalAmount: order.totalAmount,
      reason,
    }),
  });
};

const adminEmails = async () => {
  const users = await User.find({ role: 'admin' }).select('email').lean();
  return [...new Set(users.map((u) => clean(u.email)).filter(Boolean))];
};

const sendAdminAlert = async ({ subject, title, intro, rows }) => {
  const explicit = clean(process.env.ADMIN_NOTIFICATION_EMAIL);
  const recipients = explicit ? [explicit] : await adminEmails();
  await Promise.allSettled(recipients.map((to) => sendEmail({ to, subject, text: [title, ...rows.map(([k, v]) => `${k}: ${v}`)].join('\n'), html: emailShell({ title, intro, rows }) })));
};

const notifyBookingCreated = (booking) => {
  enqueueJob(`admin-booking-alert:${booking.bookingId}`, async () => {
    await PartnerNotification.create({
      title: `New booking ${booking.bookingId}`,
      message: `${booking.itemName} by ${booking.customerFullName || booking.userName}. Amount ${money(booking.totalAmount)}.`,
      type: 'notification',
      audience: 'admin',
      entityType: 'booking',
      entityId: String(booking._id),
    });
    if (booking.partnerId) {
      await PartnerNotification.create({
        title: `New booking ${booking.bookingId}`,
        message: `${booking.itemName}. Please verify payment and booking details.`,
        type: 'notification',
        audience: 'partner',
        partnerId: booking.partnerId,
        entityType: 'booking',
        entityId: String(booking._id),
      });
    }
    await sendAdminAlert({
      subject: `New booking ${booking.bookingId}`,
      title: 'New booking received',
      intro: 'A customer has submitted a booking. Admin confirmation may be required.',
      rows: bookingRows(booking),
    });
  });
};

const notifyOrderCreated = (order) => {
  enqueueJob(`admin-order-alert:${order.orderId}`, async () => {
    await PartnerNotification.create({
      title: `New order ${order.orderId}`,
      message: `${order.productName} by ${order.userName}. Amount ${money(order.totalAmount)}.`,
      type: 'notification',
      audience: 'admin',
      entityType: 'order',
      entityId: String(order._id),
    });
    await sendAdminAlert({
      subject: `New order ${order.orderId}`,
      title: 'New shop order received',
      intro: 'A customer has submitted a product order. Admin confirmation may be required.',
      rows: orderRows(order),
    });
  });
};

module.exports = {
  bookingRows,
  orderRows,
  sendBookingInvoice,
  sendOrderInvoice,
  sendBookingCancellationEmail,
  sendOrderCancellationEmail,
  notifyBookingCreated,
  notifyOrderCreated,
};
