const Booking = require('../models/Booking');
const Order = require('../models/Order');
const User = require('../models/User');
const PartnerNotification = require('../models/PartnerNotification');
const { sendEmail } = require('./email');
const { buildPdf } = require('./invoicePdf');
const { enqueueJob } = require('./jobQueue');

const clean = (value) => String(value || '').trim();
const money = (value) => `INR ${Number(value || 0).toLocaleString('en-IN')}`;
const dateText = (value) => (value ? new Date(value).toLocaleDateString('en-IN') : '');
const dateTimeText = (value) => (value ? new Date(value).toLocaleString('en-IN') : '');
const yesNo = (value) => (value ? 'Yes' : 'No');
const COMPANY_NAME = 'Vrindavan Sarthi';
const COMPANY_GSTIN = clean(process.env.COMPANY_GSTIN || process.env.VRINDAVAN_SARTHI_GSTIN || '');
const HOTEL_MARKETPLACE_DISCLAIMER =
  'Vrindavan Sarthi acts only as an online booking and payment facilitation platform. The accommodation service is provided by the hotel/property partner. The hotel/property partner is solely responsible for issuing the tax invoice to the guest and for payment of applicable GST and other taxes. This document is only a booking confirmation and payment receipt.';

const escapeHtml = (value) =>
  clean(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const tableHtml = (rows) => `
  <table cellpadding="0" cellspacing="0" role="presentation" style="width:100%;border-collapse:collapse;margin-top:14px">
    ${rows
      .filter(([, value]) => value !== undefined && value !== null && clean(value) !== '')
      .map(([label, value]) => `
        <tr>
          <td style="padding:10px 12px;border:1px solid #eadfc7;background:#fff8ea;color:#6f4b12;font:600 13px Arial,sans-serif;width:38%">${escapeHtml(label)}</td>
          <td style="padding:10px 12px;border:1px solid #eadfc7;color:#2b2018;font:13px Arial,sans-serif">${escapeHtml(value)}</td>
        </tr>
      `)
      .join('')}
  </table>
`;

const logoUrl = () => {
  const base = clean(process.env.FRONTEND_BASE_URL || process.env.PUBLIC_SITE_URL);
  if (!base) return '';
  try {
    return new URL('/vrindasarthi%20logo.jpeg', base).toString();
  } catch {
    return '';
  }
};

const emailShell = ({ title, intro, rows, totalLabel = 'Total', totalAmount = 0, reason = '' }) => `
  <div style="margin:0;padding:0;background:#f7f3ec">
    <div style="max-width:680px;margin:0 auto;padding:24px 12px">
      <div style="background:#2b120d;color:#f7c948;padding:16px 22px;border-radius:12px 12px 0 0;font:700 22px Georgia,serif;position:relative;text-align:center">
        ${logoUrl() ? `<img src="${logoUrl()}" alt="${COMPANY_NAME}" width="44" height="44" style="width:44px;height:44px;border-radius:50%;object-fit:cover;border:1px solid #f7c948;position:absolute;left:22px;top:50%;transform:translateY(-50%)" />` : ''}
        <span style="display:block;padding:0 58px">${COMPANY_NAME}</span>
      </div>
      <div style="background:#fff;border:1px solid #eadfc7;border-top:0;border-radius:0 0 12px 12px;padding:22px">
        <h1 style="margin:0 0 8px;color:#2b2018;font:700 22px Arial,sans-serif">${escapeHtml(title)}</h1>
        <p style="margin:0;color:#6b6259;font:14px/1.6 Arial,sans-serif">${escapeHtml(intro)}</p>
        ${reason ? `<div style="margin-top:16px;padding:12px 14px;border-radius:8px;background:#fff3f0;border:1px solid #ffc7bd;color:#8a2416;font:14px Arial,sans-serif"><b>Reason:</b> ${escapeHtml(reason)}</div>` : ''}
        ${tableHtml(rows)}
        <div style="margin-top:18px;padding:14px 16px;border-radius:10px;background:#f7c948;color:#2b120d;font:700 18px Arial,sans-serif;display:flex;justify-content:space-between">
          <span>${escapeHtml(totalLabel === 'Total' ? 'Total INR' : totalLabel)}</span><span style="margin-left:12px">${escapeHtml(totalLabel === 'Total' ? Number(totalAmount || 0).toLocaleString('en-IN') : money(totalAmount))}</span>
        </div>
        <p style="margin:18px 0 0;color:#8a8178;font:12px/1.5 Arial,sans-serif">For any inquiry, payment issue, booking help, order support, or cancellation assistance, contact support at 8679820256 or vrindavansarthi108@gmail.com. This email was generated by ${COMPANY_NAME}; please keep it for your records.</p>
      </div>
    </div>
  </div>
`;

const isHotelMarketplace = (booking) =>
  booking?.service_billing_model === 'hotel_marketplace' ||
  ['hotel', 'room', 'room_type'].includes(String(booking?.bookingType || ''));

const bookingRows = (booking) => {
  const hotelBooking = isHotelMarketplace(booking);
  return [
    ['Booking ID', booking.bookingId],
    ['Created On', dateTimeText(booking.createdAt)],
    ['Service Type', booking.bookingType],
    ['Billing Model', booking.service_billing_model],
    ['Service Name', booking.itemName],
    ['Property Name', hotelBooking ? String(booking.itemName || '').split(' - ')[0] : ''],
    ['Property Partner Name', hotelBooking ? booking.partnerName : ''],
    ['Customer', booking.customerFullName || booking.userName],
    ['Mobile', booking.customerMobile || booking.userPhone],
    ['Email', booking.customerEmail || booking.userEmail],
    ['Partner', hotelBooking ? '' : booking.partnerName],
    ['Booking Status', booking.bookingStatus],
    ['Verification Stage', booking.verificationStage],
    ['Check-in / Travel Date', booking.pickupDate || dateText(booking.checkIn)],
    ['Check-out', dateText(booking.checkOut)],
    ['Route', booking.bookingType === 'cab' ? `${booking.pickupLocation} to ${booking.dropLocation}` : ''],
    ['Pickup Time', booking.pickupTime],
    ['Arrival Mode', booking.arrivalMode],
    ['Arrival Time', booking.arrivalTime],
    ['Vehicle Number', booking.vehicleNumber],
    ['Cab Type', booking.cabType || booking.assignedVehicleType],
    ['Assigned Vehicle', booking.assignedVehicleName],
    ['Driver Name', booking.assignedDriverName],
    ['Driver Phone', booking.assignedDriverPhone],
    ['Guests / Passengers', booking.guests],
    ['Adults', booking.totalAdults],
    ['Children', booking.totalChildren],
    ['Travelling with Pet', booking.hasPet ? yesNo(booking.hasPet) : ''],
    ['Room Details', hotelBooking ? booking.itemName : ''],
    ['Waitlisted', booking.isWaitlisted ? 'Yes' : ''],
    [hotelBooking ? 'Room Amount' : 'Base Amount', money(booking.baseAmount || booking.checkoutSubtotal)],
    [hotelBooking ? 'Hotel GST / Hotel Taxes' : 'GST', Number(booking.taxAmount || 0) ? money(booking.taxAmount) : ''],
    [hotelBooking ? 'Platform Convenience Fee' : 'Convenience Fee', money(booking.convenienceFeeAmount)],
    [hotelBooking ? 'Total Payable' : 'Grand Total', money(booking.totalAmount)],
    [hotelBooking ? 'Advance Paid Online' : 'Advance Paid', money(booking.advanceAmount)],
    [hotelBooking ? 'Balance Payable at Property' : 'Balance Payable', money(booking.balanceAmount)],
    ['Payment Option', booking.paymentOption === 'advance_30' ? '30% advance' : 'Full payment'],
    ['Payment Method', booking.paymentMethod],
    ['Payment Status', booking.paymentStatus],
    ['UPI Transaction ID', booking.upiTransactionId],
    ['Vrindavan Sarthi GSTIN', !hotelBooking ? COMPANY_GSTIN : ''],
    ['Additional Info', booking.additionalInfo],
    ['Cancellation Reason', booking.cancellationReason],
    ['Cancellation Details', booking.cancellationDetails],
    ['Cancelled By', booking.cancelledByRole],
    ['Cancellation Deduction', Number(booking.cancellationDeductionAmount || 0) ? `${money(booking.cancellationDeductionAmount)} (${Number(booking.cancellationDeductionPercent || 12)}%)` : ''],
    ['Refundable Amount', Number(booking.refundableAmount || 0) ? money(booking.refundableAmount) : ''],
  ];
};

const orderRows = (order) => [
  ['Order ID', order.orderId],
  ['Created On', dateTimeText(order.createdAt)],
  ['Tracking ID', order.trackingId],
  ['Product', order.productName],
  ['Quantity', order.quantity],
  ['Unit Price', money(order.productPrice)],
  ['Subtotal', money(order.subtotalAmount || Number(order.productPrice || 0) * Number(order.quantity || 1))],
  ['GST', 'As applicable'],
  ['Shipping Fee', money(order.shippingFee)],
  ['Grand Total', money(order.totalAmount)],
  ['Customer', order.userName],
  ['Mobile', order.userPhone],
  ['Email', order.userEmail],
  ['Shipping Address', order.shippingAddress],
  ['Order Notes', order.orderNotes],
  ['Document Type', 'TAX INVOICE'],
  ['Billing Model', order.service_billing_model || 'ecommerce_direct'],
  ['Vrindavan Sarthi GSTIN', COMPANY_GSTIN],
  ['Payment Status', order.paymentStatus],
  ['Order Status', order.orderStatus],
  ['UPI Transaction ID', order.upiTransactionId],
  ['Courier', order.courierName],
  ['AWB Number', order.awbNumber],
  ['Tracking URL', order.trackingUrl],
  ['Tracking Notes', order.trackingNotes],
  ['Shipped At', dateTimeText(order.shippedAt)],
  ['Delivered At', dateTimeText(order.deliveredAt)],
  ['Cancellation Reason', order.cancellationReason],
  ['Cancellation Details', order.cancellationDetails],
  ['Cancelled By', order.cancelledByRole],
  ['Cancellation Deduction', Number(order.cancellationDeductionAmount || 0) ? `${money(order.cancellationDeductionAmount)} (${Number(order.cancellationDeductionPercent || 12)}%)` : ''],
  ['Refundable Amount', Number(order.refundableAmount || 0) ? money(order.refundableAmount) : ''],
];

const sendBookingInvoice = async (booking) => {
  const to = clean(booking.customerEmail || booking.userEmail);
  if (!to || booking.invoiceSentAt) return;
  const hotelBooking = isHotelMarketplace(booking);
  const documentTitle = hotelBooking ? 'BOOKING CONFIRMATION & PAYMENT RECEIPT' : 'TAX INVOICE';
  const filenamePrefix = hotelBooking ? 'booking-receipt' : 'tax-invoice';
  const rows = bookingRows(booking);
  await sendEmail({
    to,
    subject: hotelBooking
      ? `Vrindavan Sarthi booking confirmation ${booking.bookingId}`
      : `${COMPANY_NAME} tax invoice ${booking.bookingId}`,
    text: [documentTitle, ...(hotelBooking ? [HOTEL_MARKETPLACE_DISCLAIMER] : []), ...rows.map(([k, v]) => `${k}: ${v}`)].join('\n'),
    html: emailShell({
      title: documentTitle,
      intro: hotelBooking
        ? HOTEL_MARKETPLACE_DISCLAIMER
        : 'Your payment has been verified. Here are the complete booking and payment details.',
      rows,
      totalAmount: booking.totalAmount,
    }),
    attachments: [{
      filename: `${filenamePrefix}-${booking.bookingId}.pdf`,
      content: buildPdf({
        title: documentTitle,
        documentLabel: documentTitle,
        sections: [{ title: 'Booking Details', rows }],
        lines: hotelBooking ? [HOTEL_MARKETPLACE_DISCLAIMER] : [],
        totalLabel: hotelBooking ? 'Total Payable' : 'Grand Total',
        totalAmount: booking.totalAmount,
      }),
      contentType: 'application/pdf',
    }],
  });
};

const sendOrderInvoice = async (order) => {
  const to = clean(order.userEmail);
  if (!to || order.invoiceSentAt) return;
  const rows = orderRows(order);
  await sendEmail({
    to,
    subject: `${COMPANY_NAME} order invoice ${order.orderId}`,
    text: [`${COMPANY_NAME} order invoice`, ...rows.map(([k, v]) => `${k}: ${v}`)].join('\n'),
    html: emailShell({
      title: 'TAX INVOICE',
      intro: 'Your order payment has been verified. Here are the product, delivery, and payment details.',
      rows,
      totalAmount: order.totalAmount,
    }),
    attachments: [{
      filename: `invoice-${order.orderId}.pdf`,
      content: buildPdf({
        title: 'TAX INVOICE',
        documentLabel: 'TAX INVOICE',
        sections: [{ title: 'Order Details', rows }],
        totalAmount: order.totalAmount,
      }),
      contentType: 'application/pdf',
    }],
  });
};

const sendBookingCancellationEmail = async (booking, reason) => {
  const to = clean(booking.customerEmail || booking.userEmail);
  if (!to) return;
  await sendEmail({
    to,
    subject: `Booking cancelled ${booking.bookingId}`,
    text: `Your ${COMPANY_NAME} booking ${booking.bookingId} has been cancelled.\nReason: ${reason}\nCancellation charge: ${money(booking.cancellationDeductionAmount)}\nRefundable amount: ${money(booking.refundableAmount)}`,
    html: emailShell({
      title: 'Booking cancelled',
      intro: 'Your booking has been cancelled. The reason, cancellation charge, and refundable amount are shown below.',
      rows: bookingRows(booking),
      totalLabel: 'Booking Value',
      totalAmount: booking.totalAmount,
      reason,
    }),
  });
};

const sendOrderCancellationEmail = async (order, reason) => {
  const to = clean(order.userEmail);
  if (!to) return;
  await sendEmail({
    to,
    subject: `Order cancelled ${order.orderId}`,
    text: `Your ${COMPANY_NAME} order ${order.orderId} has been cancelled.\nReason: ${reason}\nCancellation charge: ${money(order.cancellationDeductionAmount)}\nRefundable amount: ${money(order.refundableAmount)}`,
    html: emailShell({
      title: 'Order cancelled',
      intro: 'Your order has been cancelled. The reason, cancellation charge, and refundable amount are shown below.',
      rows: orderRows(order),
      totalLabel: 'Order Value',
      totalAmount: order.totalAmount,
      reason,
    }),
  });
};

const adminEmails = async () => {
  const users = await User.find({ role: 'admin' }).select('email').lean();
  return [...new Set(users.map((u) => clean(u.email)).filter(Boolean))];
};

const sendAdminAlert = async ({ subject, title, intro, rows }) => {
  const explicit = clean(process.env.ADMIN_NOTIFICATION_EMAIL);
  const recipients = explicit ? [explicit] : await adminEmails();
  await Promise.allSettled(recipients.map((to) => sendEmail({ to, subject, text: [title, ...rows.map(([k, v]) => `${k}: ${v}`)].join('\n'), html: emailShell({ title, intro, rows }) })));
};

const notifyBookingCreated = (booking) => {
  enqueueJob(`admin-booking-alert:${booking.bookingId}`, async () => {
    await PartnerNotification.create({
      title: `New booking ${booking.bookingId}`,
      message: `${booking.itemName} by ${booking.customerFullName || booking.userName}. Amount ${money(booking.totalAmount)}.`,
      type: 'notification',
      audience: 'admin',
      entityType: 'booking',
      entityId: String(booking._id),
    });
    if (booking.partnerId) {
      await PartnerNotification.create({
        title: `New booking ${booking.bookingId}`,
        message: `${booking.itemName}. Please verify payment and booking details.`,
        type: 'notification',
        audience: 'partner',
        partnerId: booking.partnerId,
        entityType: 'booking',
        entityId: String(booking._id),
      });
    }
    await sendAdminAlert({
      subject: `New booking ${booking.bookingId}`,
      title: 'New booking received',
      intro: 'A customer has submitted a booking. Admin confirmation may be required.',
      rows: bookingRows(booking),
    });
  });
};

const notifyOrderCreated = (order) => {
  enqueueJob(`admin-order-alert:${order.orderId}`, async () => {
    await PartnerNotification.create({
      title: `New order ${order.orderId}`,
      message: `${order.productName} by ${order.userName}. Amount ${money(order.totalAmount)}.`,
      type: 'notification',
      audience: 'admin',
      entityType: 'order',
      entityId: String(order._id),
    });
    await sendAdminAlert({
      subject: `New order ${order.orderId}`,
      title: 'New shop order received',
      intro: 'A customer has submitted a product order. Admin confirmation may be required.',
      rows: orderRows(order),
    });
  });
};

module.exports = {
  bookingRows,
  orderRows,
  sendBookingInvoice,
  sendOrderInvoice,
  sendBookingCancellationEmail,
  sendOrderCancellationEmail,
  notifyBookingCreated,
  notifyOrderCreated,
};
