plugins {
    id "com.android.application"
    id "com.google.gms.google-services"
}

android {
    namespace "in.vrindavansarthi.alarm"
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "in.vrindavansarthi.alarm"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
        buildConfigField "String", "APP_URL", "\"https://www.vrindavansarthi.in/admin\""
        buildConfigField "String", "API_BASE_URL", "\"https://www.vrindavansarthi.in/api\""
    }
}

dependencies {
    implementation platform("com.google.firebase:firebase-bom:33.7.0")
    implementation "com.google.firebase:firebase-messaging"
    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation "androidx.core:core:1.15.0"
}
