export const LANDMARK_OPTIONS = [
  'Banke Bihari Temple',
  'Prem Mandir',
  'ISKCON Temple',
  'Radha Raman Temple',
  'Nidhivan',
  'Seva Kunj',
  'Shahji Temple',
  'Madan Mohan Temple',
  'Radha Vallabh Temple',
  'Rangji Temple',
  'Katyayani Peeth',
  'Maa Vaishno Devi Dham',
  'Pagal Baba Temple',
  'Priyakant Ju Temple',
  'Kesi Ghat',
  'Yamuna Ghat',
  'Dwarikadhish',
  'Dwarikadhish Temple',
  'Shri Krishna Janmabhoomi',
  'Janmbhoomi',
  'Janmabhoomi Temple',
  'Vishram Ghat',
  'Potra Kund',
  'Bhuteshwar Mahadev Temple',
  'Rangeshwar Mahadev Temple',
  'Chamunda Devi Temple',
  'Gita Mandir',
  'Birla Mandir',
  'Shri Krishna Balaram Mandir',
  'Govardhan',
  'Govardhan Parikrama',
  'Giriraj Ji Temple',
  'Daan Ghati Temple',
  'Mukharvind Temple',
  'Mansi Ganga',
  'Kusum Sarovar',
  'Radha Kund',
  'Shyam Kund',
  'Jatipura',
  'Puchari Ka Lautha',
  'Barsana',
  'Barsana Temple',
  'Barshana',
  'Barshana Temple',
  'Radha Rani Temple',
  'Kirti Mandir',
  'Maan Mandir',
  'Kushal Bihari Temple',
  'Mor Kutir',
  'Nandgaon',
  'Nand Bhawan',
  'Pan Sarovar',
  'Gokul',
  'Raman Reti',
  'Chaurasi Khamba',
  'Brahmand Ghat',
  'Mahavan',
  'Baldeo',
  'Dauji Temple',
  'Raval',
  'Rawal',
  'Vrindavan',
  'Lohvan',
  'Bhandirvan',
  'Kamyavan',
  'Brij Chaurasi Kos Parikrama',
  'Kokilavan',
  'Kokilavan Shani Temple',
  'Kosi Kalan',
  'Chhata',
  'Mathura',
];

export const OTHER_LANDMARK_OPTION = 'Others';
